#!/bin/bash

case "$1" in
    "cpu")
        if [[ "$2" == "getinfo" ]]; then
            lscpu
        fi
        ;;
    "memory")
        if [[ "$2" == "getinfo" ]]; then
            free
        fi
        ;;
    "user")
        if [[ "$2" == "create" ]]; then
            sudo useradd -m "$3"
        elif [[ "$2" == "list" ]]; then
            if [[ "$3" == "--sudo-only" ]]; then
                awk '/^%sudo/ { for (i=4;i<=NF;i++) { print $i } }' /etc/sudoers
            else
                cut -d: -f1 /etc/passwd
            fi
        fi
        ;;
    "file")
        if [ "$2" == "getinfo" ]
    then
        if [ -f "$3" ] 
        then
            echo "File: $3"
            echo "Access: $(stat -c %A $3)"
            echo "Size(B): $(stat -c %s $3)"
            echo "Owner: $(stat -c %U $3)"
            echo "Modify: $(stat -c %y $3)" 
        fi 
        
        if [ "$3" == "--permission" ]  || [ "$3" == "-p" ]
        then 
            FILE_INFO="$(ls -l $4)"
            FILE_ACCESS=$(echo "$FILE_INFO" | awk '{print $1}')
            echo "Permission: $FILE_ACCESS"
        fi
         if [ "$3" == "--owner" ]  || [ "$3" == "-o" ]
        then 
            FILE_INFO="$(ls -l $4)"
            FILE_OWNER=$(echo "$FILE_INFO" | awk '{print $3}')
             echo "Owner: $FILE_OWNER"
        fi  
         if [ "$3" == "--size" ]  || [ "$3" == "-s" ]
        then 
            FILE_INFO="$(ls -l $4)"
            FILE_SIZE=$(echo "$FILE_INFO" | awk '{print $5}')
             echo "SIZE: $FILE_SIZE"
        fi       
         if [ "$3" == "--last-modified" ]  
        then
             FILE_MODIFIED=$(stat -c %y $4)
             echo "MODIFY: $FILE_MODIFIED"
        fi                  
    else
        echo "Usage: internsctl file getinfo <file-name>"
        echo "Get information about a file"
    fi
        ;;
    *)
        echo "Invalid command"
        ;;
esac
