#!/bin/bash


if [[ "$1" == "cpu" ]]; then
  
  if [[ "$2" == "getinfo" ]]; then
   
    lscpu
  else
    
    echo "Invalid sub-command. Usage: internsctl cpu getinfo"
  fi


elif [[ "$1" == "memory" ]]; then
  
  if [[ "$2" == "getinfo" ]]; then
    
    free -h
  else
    
    echo "Invalid sub-command. Usage: internsctl memory getinfo"
  fi


elif [[ "$1" == "user" ]]; then
  
  if [[ "$2" == "create" ]]; then
   
    if [[ -n "$3" ]]; then
     
      useradd -m "$3"
    else
      
      echo "Please provide a username. Usage: internsctl user create <username>"
    fi
  
  elif [[ "$2" == "list" ]]; then
    
    if [[ "$3" == "--sudo-only" ]]; then
      
      grep -Po '^sudo.+:\K.*$' /etc/group | tr ',' '\n'
    else
      
      cut -d: -f1,3 /etc/passwd | awk -F: '$2 >= 1000 && $2 < 65534 { print $1 }'
    fi
  else
    
    echo "Invalid sub-command. Usage: internsctl user create <username> OR internsctl user list [--sudo-only]"
  fi

else
  
  echo "Invalid command. Usage: internsctl [cpu|memory|user]"
fi

